%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\von_Server\ETH\BSc Physics\5\Praktikum 3\Semiconductor\data\data2.xlsx
%    Worksheet: Tabelle1
%
% Auto-generated by MATLAB on 20-Nov-2018 17:30:23

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Tabelle1";
opts.DataRange = "A2:F100";

% Specify column names and types
opts.VariableNames = ["T_C", "errT", "V4", "errV4", "I_mA", "errI_mA"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [2, 3, 4, 5, 6], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 3, 4, 5, 6], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\von_Server\ETH\BSc Physics\5\Praktikum 3\Semiconductor\data\data2.xlsx", opts, "UseExcel", false);

%% Convert to output type
T_C = tbl.T_C;
errT = tbl.errT;
V4 = tbl.V4;
errV4 = tbl.errV4;
I_mA = tbl.I_mA;
errI_mA = tbl.errI_mA;

%% Clear temporary variables
clear opts tbl