%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\von_Server\ETH\BSc Physics\5\Praktikum 3\Semiconductor\data\data.xlsx
%    Worksheet: Tabelle1
%
% Auto-generated by MATLAB on 20-Nov-2018 17:38:08

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Tabelle1";
opts.DataRange = "A2:G23";

% Specify column names and types
opts.VariableNames = ["TC", "ImuA", "V4mV", "err_V4mV", "V2mV", "err_V2mV", "err_ImuA"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\von_Server\ETH\BSc Physics\5\Praktikum 3\Semiconductor\data\data.xlsx", opts, "UseExcel", false);

%% Convert to output type
TC = tbl.TC;
ImuA = tbl.ImuA;
V4mV = tbl.V4mV;
err_V4mV = tbl.err_V4mV;
V2mV = tbl.V2mV;
err_V2mV = tbl.err_V2mV;
err_ImuA = tbl.err_ImuA;

%% Clear temporary variables
clear opts tbl